repo: 'retro-sign'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    locked: true

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box', 'The `border-box` layout model is needed for this assignment—use the `borderbox` snippet']
      - ['*', 'box-sizing', 'inherit', 'The `border-box` layout model is needed for this assignment—use the `borderbox` snippet']
      - ['body', 'margin', '0']
      - ['.btn', 'cursor', 'pointer']
      - ['.btn:active']
    search:
      - '\.lines'
      - '\.engage'
      - 'path'
      - '\:nth-child\('
      - '@keyframes'
      - 'stroke-dasharray'
      - 'animation'
      - 'transition'
      - 'transition-delay'

js:
  - path: 'js/main.js'
    valid: true
    bestPractices: true
    search:
      - "\\$\\('svg'\\)"
      - "\\$\\('\\.btn'\\)"
      - "\\.on\\('click'\\, function \\("
      - ['\.(has|toggle|add|remove)Class\(', 'Expected class manipulation']

screenshots:
  - path: 'index.html'
    sizes: [980]

functionality:
  - path: 'index.html'
    tests:
      - |
        let totalEvents = 3;
        let svg = $('svg');
        let oldClassLength = svg.classList.length;
        let btn = $('.btn');
        let btnFill = $('path:nth-child(2)', btn);
        let oldBtnFill = css(btnFill).fill;
        let path = $('.lines path');
        let oldAnimName = css(path).animationName;
        let oldStrokeDasharray = css(path).strokeDasharray;
        let letterE = $('.engage path:first-child');
        let oldLetterEFill = css(letterE).fill;

        var checkPass = function () {
          if (totalEvents <= 0) pass();
        };

        on('.btn path:nth-child(2)', 'transitionend', function (err, ev) {
          if (err) fail('The transition on the button’s coloured setion never ends—check that is has a transition');
          if (oldBtnFill == css(btnFill).fill) fail('The button doesn’t change colour');
          totalEvents--;
          checkPass();
        });

        on('.lines path', 'animationend', function (err, ev) {
          if (err) fail('The animation on the lines never ends—check that they have an animation');
          if (oldStrokeDasharray == css(path).strokeDasharray) fail('The `stroke-dasharray` doesn’t change in the animation');
          totalEvents--;
          checkPass();
        });

        on('.engage path:first-child', 'transitionend', function (err, ev) {
          if (err) fail('The transition never ends on the letters—check that they have a transision');
          if (oldLetterEFill == css(letterE).fill) fail('The letters don’t change colour');
          totalEvents--;
          checkPass();
        });

        btn.dispatchEvent(ev('click'));
        if (svg.classList.length <= oldClassLength) fail('The class does’t change on the SVG');
        if (oldAnimName == css(path).animationName) fail('An animation isn’t added to the lines');
